### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by santoshachari** [rundef/laravel_wordpress#2]
Hey Mate, 

I see the links in readme doesn't work. Can you check?

**Comment by rundef** [comment]
Hi, 

Yes, sorry my blog was down. It's working now.

**Comment by santoshachari** [comment]
Thanks @rundef . Question: I want to use laravel backend, and wordpress frontend. Or let's say some pages will be shown from wordpress (home page, blog etc), and some routes will be handled by laravel. 

What would be the best way to do it?
